# Generated by Django 5.2.5 on 2025-08-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('heure_cree', models.DateTimeField(auto_now_add=True)),
                ('heure_modifiee', models.DateTimeField(auto_now=True)),
                ('auteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Utilisateur'), ('guest', 'Visiteur')], default='guest', editable=False, max_length=20)),
                ('cv', models.FileField(upload_to='cv/')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='temoignages/')),
                ('heure_cree', models.DateTimeField(auto_now_add=True)),
                ('heure_modifiee', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atsweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('heure_cree', models.DateTimeField(auto_now_add=True)),
                ('heure_modifiee', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atsweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='realisations/')),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('heure_cree', models.DateTimeField(auto_now_add=True)),
                ('heure_modifiee', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='Atsweb.technology')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atsweb.user')),
            ],
        ),
    ]
