# Generated by Django 5.2.5 on 2025-08-19 11:33

from django.db import migrations
from django.contrib.auth import get_user_model

def create_default_admins(apps, schema_editor):
    User = get_user_model()
    
    default_admins = [
        {
            'username': 'admin1',
            'email': 'admin1@example.com',
            'password': 'adminpass',
            'role': 'admin'
        },
        {
            'username': 'superadmin',
            'email': 'superadmin@example.com',
            'password': 'superadminpass',
            'role': 'admin'
        }
    ]

    for admin_data in default_admins:
        if not User.objects.filter(username=admin_data['username']).exists():
            User.objects.create_user(
                username=admin_data['username'],
                email=admin_data['email'],
                password=admin_data['password'],
                role='admin'
            )

def reverse_default_admins(apps, schema_editor):
    User = get_user_model()
    User.objects.filter(username__in=['admin1', 'superadmin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Atsweb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admins, reverse_default_admins),
    ]
