# Generated by Django 5.2.5 on 2025-08-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atsweb', '0004_candidature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
