# Generated by Django 5.2.5 on 2025-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atsweb', '0005_remove_user_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='start_month',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
